export default
[
  {
    code: 'MVD001',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Hà Nội',
    from_province_code: 'HN',
    to_province: 'Hồ Chí Minh',
    to_province_code: 'HCM',
    flight: 'VNA121',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 1,
    note: 'Mô tả',
    flight_num: 'Ngày',
    total: 10
  },
  {
    code: 'MVD002',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Hà Nội',
    from_province_code: 'HN',
    to_province: 'Đà Nẵng',
    to_province_code: 'DN',
    flight: 'VNA122',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 2,
    note: 'Mô tả',
    flight_num: 'Tuần',
    total: 50
  },
  {
    code: 'MVD003',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Đà Nẵng',
    from_province_code: 'DN',
    to_province: 'Hồ Chí Minh',
    to_province_code: 'HCM',
    flight: 'VNA123',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 3,
    note: 'Mô tả',
    flight_num: 'Tháng',
    total: 150
  },
  {
    code: 'MVD004',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Cần Thơ',
    from_province_code: 'CT',
    to_province: 'Hồ Chí Minh',
    to_province_code: 'HCM',
    flight: 'VNA124',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 4,
    note: 'Mô tả',
    total: 50
  },
  {
    code: 'MVD005',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Hồ Chí Minh',
    from_province_code: 'HCM',
    to_province: 'Đà Nẵng',
    to_province_code: 'DN',
    flight: 'VNA125',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 5,
    note: 'Mô tả',
    total: 150
  },
  {
    code: 'MVD001',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Hà Nội',
    from_province_code: 'HN',
    to_province: 'Hồ Chí Minh',
    to_province_code: 'HCM',
    flight: 'VNA121',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 6,
    note: 'Mô tả',
    total: 50
  },
  {
    code: 'MVD001',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Hà Nội',
    from_province_code: 'HN',
    to_province: 'Hồ Chí Minh',
    to_province_code: 'HCM',
    flight: 'VNA121',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 7,
    note: 'Mô tả',
    total: 50
  },
  {
    code: 'MVD001',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Hà Nội',
    from_province_code: 'HN',
    to_province: 'Hồ Chí Minh',
    to_province_code: 'HCM',
    flight: 'VNA121',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 1,
    note: 'Mô tả',
    total: 50
  },
  {
    code: 'MVD001',
    start_date: '14:20 01/05/2021',
    order_user: 'Nguyen Van A',
    from_province: 'Hà Nội',
    from_province_code: 'HN',
    to_province: 'Hồ Chí Minh',
    to_province_code: 'HCM',
    flight: 'VNA121',
    weight: '1000 gram',
    shipper: 'Shipper 1',
    step: 1,
    note: 'Mô tả',
    total: 50
  }
]
